stages:
  data_ingestion:
    cmd: python src/data_ingestion.py
    deps:
    - src/data_ingestion.py
    outs:
    - data/raw
  data_preproprocessing:
    cmd: python src/data_preprocessing.py
    deps:
    - data/raw
    - src/data_preprocessing.py
    outs:
    - data/processed
  feature_engineering:
    cmd: python src/feature_engineering.py
    deps:
    - data/processed
    - src/feature_engineering.py
    outs:
    - data/features
  model_training:
    cmd: python src/model_training.py
    deps:
    - data/features
    - src/model_training.py
    outs:
    - model.pkl
  model_evaluation:
    cmd: python src/model_evaluation.py
    deps:
    - model.pkl
    - src/model_evaluation.py
    metrics:
    - metrics.json
